// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Departamento de Informática del Hospital Santiago Apóstol (Miranda de Ebro) de hsap",
            "url": "http://www.hsap.sacyl.es/",
            "email": "informatica.hsap@saludcastillayleon.es"
        },
        "license": {
            "name": "Public domain",
            "url": "https://creativecommons.org/publicdomain/zero/1.0/"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "produces": [
                    "text/plain"
                ],
                "summary": "Shows API description",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/IPscan": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Displays JSON w/ matching ports on network switches for a given IP address",
                "parameters": [
                    {
                        "type": "string",
                        "description": "IP address to scan",
                        "name": "ipToFind",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/mainSwitchArpTable": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Displays JSON w/ main switch ARP table (IP =\u003e MAC) restricted by VLAN",
                "parameters": [
                    {
                        "type": "string",
                        "description": "VLAN identifier to filter out ARP table entries",
                        "name": "vlanFilter",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/swagger": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Displays JSON w/ API doc built by swaggo",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/test": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Performs a minimal test showing API ip address, server time",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "localhost:3333",
	BasePath:    "/",
	Schemes:     []string{},
	Title:       "goSwitchSNMP API",
	Description: "API en goLang que consulta por SNMP los switches de red",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
